SELECT U.USER_ID, U.USERNAME, T.TRAINING_ID, T.TRAINING_DATE, COUNT(T.TRAINING_ID)
FROM "User" U
JOIN "Training_details" T ON
U.USER_ID = T.USER_ID
GROUP BY U.USER_ID, TRAINING_ID, U.USERNAME, T.TRAINING_DATE
HAVING COUNT(TRAINING_ID) > 1
ORDER BY TRAINING_DATE DESC;